// ── PLACE DATA ──────────────────────────────────────────────────────────────
const PLACES = [
  {
    id:"schmuck",name:"Schmuck",neighbourhood:"Lower East Side",type:"Bar/Wine Bar",
    address:"1st Ave, Lower East Side",hours:"Open till 2 am",
    coordinates:[-73.9874,40.7223],
    tags:["Bar","Nightlife"],
    transit:{name:"Delancey St F/M/J/Z",tags:["Well Lit","Busy"],fromNYU:"Take the F train from Jay St–MetroTech (8 min). Exit at Delancey St, 4 min walk."},
    observations:{
      day:[
        {text:"Sparse crowd most afternoons — tables easy to get.",tags:["Atmosphere & Vibe"]},
        {text:"Natural light through the front windows until early evening.",tags:["Atmosphere & Vibe"]},
        {text:"Staff chatty when quiet — good spot for solo visits.",tags:["Atmosphere & Vibe"]},
        {text:"Music low enough to hold a full conversation.",tags:["Noise/Crowd"]},
      ],
      night:[
        {text:"Gets noticeably fuller after 10 pm on weekends.",tags:["Noise/Crowd"]},
        {text:"Back section stays quieter even when the front fills up.",tags:["Atmosphere & Vibe"]},
        {text:"Line forms outside around midnight on Fri–Sat.",tags:["Noise/Crowd"]},
        {text:"Cab drop-offs cluster on the corner — easy to get one leaving.",tags:["Getting there/home"]},
        {text:"Louder after 11 pm but conversation still possible near the bar.",tags:["Noise/Crowd"]},
      ],
    },
    areaActivity:["Street active most evenings with foot traffic from nearby restaurants.","Delivery bikes move through the block regularly.","Corner bodega open late."],
  },
  {
    id:"superbueno",name:"Superbueno",neighbourhood:"Lower East Side",type:"Bar/Restaurant",
    address:"183 Eldridge St, Lower East Side",hours:"Open till 1 am",
    coordinates:[-73.9866,40.7195],
    tags:["Bar","Restaurant","Latin"],
    transit:{name:"Delancey St F/M/J/Z",tags:["Well Lit","Busy"],fromNYU:"Take the F train from Jay St–MetroTech (8 min). Exit at Delancey St, 5 min walk."},
    observations:{
      day:[
        {text:"Lunch crowd mostly locals — calm and unfussy.",tags:["Atmosphere & Vibe"]},
        {text:"Outdoor sidewalk seating available until evening.",tags:["Atmosphere & Vibe"]},
        {text:"Service attentive when it's not slammed.",tags:["Atmosphere & Vibe"]},
        {text:"Easy to walk in without a reservation before 6 pm.",tags:["Noise/Crowd"]},
      ],
      night:[
        {text:"Gets lively when there's live music — check their schedule.",tags:["Atmosphere & Vibe"]},
        {text:"Bar area fills up quickly after 9 pm on weekends.",tags:["Noise/Crowd"]},
        {text:"Back dining room stays calmer than the front.",tags:["Atmosphere & Vibe"]},
        {text:"Street outside busy — watch for cyclists.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Active block — several venues mean steady foot traffic.","Rideshares plentiful on Delancey a short walk away.","Area quiets down after 2 am."],
  },
  {
    id:"attaboy",name:"Attaboy",neighbourhood:"Lower East Side",type:"Cocktail Bar",
    address:"134 Eldridge St, Lower East Side",hours:"Open till 4 am",
    coordinates:[-73.9903,40.7212],
    tags:["Cocktail Bar","Late Night"],
    transit:{name:"Essex St J/M/Z",tags:["Quiet at Night"],fromNYU:"Take the A/C from Jay St to Broadway–Lafayette, transfer to J/M/Z (14 min). 3 min walk."},
    observations:{
      day:[
        {text:"Opens late afternoon — good for an early drink before dinner.",tags:["Atmosphere & Vibe"]},
        {text:"Bartenders focused and happy to talk through options.",tags:["Atmosphere & Vibe"]},
        {text:"No menu — they make what suits you.",tags:["Atmosphere & Vibe"]},
        {text:"Rarely crowded before 7 pm.",tags:["Noise/Crowd"]},
      ],
      night:[
        {text:"Standing room only most nights after 10 pm.",tags:["Noise/Crowd"]},
        {text:"Wait can be 20–30 min on weekends but it moves.",tags:["Noise/Crowd"]},
        {text:"Dimly lit — bring patience for your eyes adjusting.",tags:["Atmosphere & Vibe"]},
        {text:"Crowd generally low-key despite the volume.",tags:["Atmosphere & Vibe"]},
        {text:"Late nights here tend to go long — plan accordingly.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Eldridge St relatively quiet vs the main strip.","Foot traffic picks up on weekends after midnight.","Nearby cafes close early — options thin after 9 pm."],
  },
  {
    id:"julius",name:"Julius' Bar",neighbourhood:"West Village",type:"Bar",
    address:"159 W 10th St, West Village",hours:"Open till 4 am",
    coordinates:[-74.0025,40.7336],
    tags:["Bar","Historic","West Village"],
    transit:{name:"Christopher St A/C/E",tags:["Well Lit","Safe"],fromNYU:"Take the A/C/E from Jay St–MetroTech to 14th St, then 1 stop to Christopher St (18 min)."},
    observations:{
      day:[
        {text:"One of NYC's oldest bars — afternoon crowd reflects that.",tags:["Atmosphere & Vibe"]},
        {text:"Quiet enough to read or have a slow drink.",tags:["Noise/Crowd"]},
        {text:"Regulars at the bar; tourists take the tables.",tags:["Atmosphere & Vibe"]},
        {text:"No frills, good beer, reasonable prices for the area.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Busier after 9 pm but never feels chaotic.",tags:["Noise/Crowd"]},
        {text:"Jukebox gets louder as the night goes on.",tags:["Noise/Crowd"]},
        {text:"Mixed crowd — locals, visitors, regulars.",tags:["Atmosphere & Vibe"]},
        {text:"Easy to find a spot even on weekends.",tags:["Noise/Crowd"]},
      ],
    },
    areaActivity:["West Village streets well-lit and walkable.","Multiple subway options at Christopher St.","Block is residential — tends to stay calm."],
  },
  {
    id:"gage",name:"Gage & Tollner",neighbourhood:"Downtown Brooklyn",type:"Restaurant/Bar",
    address:"372 Fulton St, Downtown Brooklyn",hours:"Open till 11 pm",
    coordinates:[-73.9898,40.6917],
    tags:["Restaurant","Bar","Brooklyn"],
    transit:{name:"Jay St–MetroTech A/C/F/R",tags:["Well Lit","Busy"],fromNYU:"5 min walk from NYU Brooklyn campus — closest venue to campus."},
    observations:{
      day:[
        {text:"Lunch quieter — good option if you want space.",tags:["Noise/Crowd"]},
        {text:"Large dining room; noise distributes well.",tags:["Noise/Crowd"]},
        {text:"Reservations easier mid-week.",tags:["Atmosphere & Vibe"]},
        {text:"Good natural light through the front windows.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Dinner service fills the room — livelier atmosphere.",tags:["Atmosphere & Vibe"]},
        {text:"Noise rises after 7:30 pm but stays manageable.",tags:["Noise/Crowd"]},
        {text:"Bar area gets a pre-theatre crowd early evening.",tags:["Atmosphere & Vibe"]},
        {text:"Fulton St outside busy on weekend nights.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Downtown Brooklyn busy during commute hours.","Fulton St Mall active — foot traffic varies.","Multiple subway lines at Jay St make transit easy."],
  },
  {
    id:"saraghina",name:"Saraghina",neighbourhood:"Bed-Stuy, Brooklyn",type:"Restaurant/Bar",
    address:"435 Halsey St, Bed-Stuy",hours:"Open till 10:30 pm",
    coordinates:[-73.9393,40.6867],
    tags:["Restaurant","Bar","Brooklyn","Neighbourhood"],
    transit:{name:"Halsey St J",tags:["Quiet","Residential"],fromNYU:"Take the J from Marcy Ave to Halsey St (16 min). 3 min walk."},
    observations:{
      day:[
        {text:"Weekend brunch draws a queue — arrive early.",tags:["Noise/Crowd"]},
        {text:"Garden out back calm on weekday afternoons.",tags:["Atmosphere & Vibe"]},
        {text:"Neighbourhood feel — familiar faces, relaxed pace.",tags:["Atmosphere & Vibe"]},
        {text:"Coffee service good; easy to linger.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Dinner wait can run 30–45 min on weekends.",tags:["Noise/Crowd"]},
        {text:"Garden seating quieter than the main room.",tags:["Atmosphere & Vibe"]},
        {text:"Street outside calm post-dinner.",tags:["Safety & Comfort"]},
        {text:"Mostly residential once the restaurant crowd disperses.",tags:["Safety & Comfort"]},
      ],
    },
    areaActivity:["Halsey St residential — evenings relatively quiet.","Short walk to J/Z trains.","Active foot traffic during weekend mornings."],
  },

  // ── LOWER EAST SIDE ──────────────────────────────────────────────────────
  {
    id:"barrio_chino",name:"Barrio Chino",neighbourhood:"Lower East Side",type:"Bar/Restaurant",
    address:"253 Broome St, Lower East Side",hours:"Open till 2 am",
    coordinates:[-73.9928,40.7163],
    tags:["Bar","Mezcal","Mexican"],
    transit:{name:"Delancey St F/M/J/Z",tags:["Well Lit","Busy"],fromNYU:"Take the F from Jay St–MetroTech (8 min). Exit Delancey, 6 min walk west."},
    observations:{
      day:[
        {text:"Near-empty most afternoons — good for a quiet mezcal.",tags:["Atmosphere & Vibe"]},
        {text:"Kitchen does solid tacos at lunch, unpretentious crowd.",tags:["Atmosphere & Vibe"]},
        {text:"Bar staff knowledgeable and happy to explain the mezcal list.",tags:["Atmosphere & Vibe"]},
        {text:"Comfortable to sit alone at the bar.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Fills up steadily after 9 pm, especially on weekends.",tags:["Noise/Crowd"]},
        {text:"Warm lighting keeps the atmosphere intimate even when busy.",tags:["Atmosphere & Vibe"]},
        {text:"Music gets louder as the night progresses.",tags:["Noise/Crowd"]},
        {text:"Broome St is lively but manageable — rideshares easy to get.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Broome St sees steady foot traffic into the early hours.","Mixed residential and bar crowd in the area.","Bodega on the corner open late."],
  },
  {
    id:"the_ten_bells",name:"The Ten Bells",neighbourhood:"Lower East Side",type:"Wine Bar",
    address:"247 Broome St, Lower East Side",hours:"Open till 1 am",
    coordinates:[-73.9930,40.7165],
    tags:["Wine Bar","Natural Wine"],
    transit:{name:"Delancey St F/M/J/Z",tags:["Well Lit"],fromNYU:"Take the F from Jay St–MetroTech (8 min). 6 min walk."},
    observations:{
      day:[
        {text:"Quiet and candlelit even during the day — genuinely cosy.",tags:["Atmosphere & Vibe"]},
        {text:"Good for long conversations over a glass of natural wine.",tags:["Atmosphere & Vibe"]},
        {text:"Staff give good recommendations without being pushy.",tags:["Atmosphere & Vibe"]},
        {text:"Tables fill up fast even at lunch — worth arriving early.",tags:["Noise/Crowd"]},
      ],
      night:[
        {text:"Candles, close tables, and low music — reliably intimate.",tags:["Atmosphere & Vibe"]},
        {text:"Gets crowded fast after 8 pm; standing room by 10.",tags:["Noise/Crowd"]},
        {text:"Crowd tends to be wine-focused and relatively low-key.",tags:["Atmosphere & Vibe"]},
        {text:"The narrow space means it gets loud when full.",tags:["Noise/Crowd"]},
      ],
    },
    areaActivity:["Broome St corridor has a lot of similar bars — late night foot traffic steady.","Quiet side streets nearby offer calmer walking routes.","Rideshares available on Delancey."],
  },
  {
    id:"mr_purple",name:"Mr. Purple",neighbourhood:"Lower East Side",type:"Bar/Rooftop",
    address:"180 Orchard St, Lower East Side",hours:"Open till 2 am",
    coordinates:[-73.9882,40.7208],
    tags:["Rooftop","Bar","Views"],
    transit:{name:"2nd Ave F",tags:["Well Lit","Busy"],fromNYU:"Take the F from Jay St (10 min). Exit 2nd Ave, 5 min walk."},
    observations:{
      day:[
        {text:"Rooftop pool area open in season — worth checking their schedule.",tags:["Atmosphere & Vibe"]},
        {text:"Views of lower Manhattan are the main draw during the day.",tags:["Atmosphere & Vibe"]},
        {text:"Quieter before 5 pm — easier to get a spot on the terrace.",tags:["Noise/Crowd"]},
        {text:"Hotel bar vibe — polished and well-staffed.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Gets very crowded on weekend nights — expect a wait.",tags:["Noise/Crowd"]},
        {text:"City views at night are the main event.",tags:["Atmosphere & Vibe"]},
        {text:"Dress code loosely enforced but smart casual is safest.",tags:["Safety & Comfort"]},
        {text:"Elevator situation can cause a bottleneck when busy.",tags:["Getting there/home"]},
        {text:"Orchard St below gets noisy late on weekends.",tags:["Noise/Crowd"]},
      ],
    },
    areaActivity:["Orchard St is one of the busiest LES blocks on weekend nights.","Well-lit and busy — feels safe even late.","Rideshares easy on Houston St nearby."],
  },
  {
    id:"beauty_bar_les",name:"Beauty Bar",neighbourhood:"Lower East Side",type:"Bar",
    address:"231 E 14th St, Lower East Side",hours:"Open till 4 am",
    coordinates:[-73.9843,40.7320],
    tags:["Bar","Late Night","Dive"],
    transit:{name:"1st Ave L",tags:["Busy","Late Night"],fromNYU:"Take the F to Jay St, transfer to A/C to 14th St (18 min). Short walk."},
    observations:{
      day:[
        {text:"Rarely open before evening — check hours before going.",tags:["Atmosphere & Vibe"]},
        {text:"Kitschy salon decor makes it a fun early drinks spot.",tags:["Atmosphere & Vibe"]},
        {text:"Very laid-back crowd in the early hours.",tags:["Noise/Crowd"]},
        {text:"Cheap drinks for the neighbourhood.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Packed after midnight — one of the real late-night spots in the area.",tags:["Noise/Crowd"]},
        {text:"Loud music, crowded floor — not a conversation bar after 11.",tags:["Noise/Crowd"]},
        {text:"Crowd is generally young and high-energy.",tags:["Atmosphere & Vibe"]},
        {text:"14th St is well-lit and busy — easy to get home from.",tags:["Getting there/home"]},
        {text:"Staff are efficient and unfussy.",tags:["Atmosphere & Vibe"]},
      ],
    },
    areaActivity:["14th St corridor is active until very late.","L train runs frequently — good late-night transit option.","Area is lively but can get rowdy near closing time."],
  },
  {
    id:"pig_and_khao",name:"Pig & Khao",neighbourhood:"Lower East Side",type:"Restaurant/Bar",
    address:"68 Clinton St, Lower East Side",hours:"Open till 11 pm",
    coordinates:[-73.9856,40.7185],
    tags:["Restaurant","Southeast Asian","Bar"],
    transit:{name:"Delancey St F/M/J/Z",tags:["Well Lit"],fromNYU:"Take the F from Jay St (8 min). 7 min walk."},
    observations:{
      day:[
        {text:"Lunch is relaxed — easier to get a table than at dinner.",tags:["Noise/Crowd"]},
        {text:"Bar area good for eating solo without a reservation.",tags:["Safety & Comfort"]},
        {text:"Friendly, attentive service during quieter hours.",tags:["Atmosphere & Vibe"]},
        {text:"Clinton St is calm during the day.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Dinner gets loud — the open kitchen adds to the energy.",tags:["Noise/Crowd"]},
        {text:"Reservations strongly recommended on weekends.",tags:["Noise/Crowd"]},
        {text:"Bar seats are walk-in only and go fast.",tags:["Atmosphere & Vibe"]},
        {text:"Great for groups — the sharing plates format works well.",tags:["Atmosphere & Vibe"]},
      ],
    },
    areaActivity:["Clinton St is relatively quiet compared to the main LES strip.","Residential block — area calms down after midnight.","Rideshares available on Delancey."],
  },
  {
    id:"welcome_to_the_johnsons",name:"Welcome to the Johnsons",neighbourhood:"Lower East Side",type:"Dive Bar",
    address:"123 Rivington St, Lower East Side",hours:"Open till 4 am",
    coordinates:[-73.9867,40.7197],
    tags:["Dive Bar","Late Night","Cheap"],
    transit:{name:"Delancey St F/M/J/Z",tags:["Well Lit"],fromNYU:"Take the F from Jay St (8 min). 5 min walk."},
    observations:{
      day:[
        {text:"Classic dive bar energy even in the afternoon.",tags:["Atmosphere & Vibe"]},
        {text:"Cheap beer, pool table, no pretension.",tags:["Atmosphere & Vibe"]},
        {text:"Regulars at the bar most afternoons.",tags:["Noise/Crowd"]},
        {text:"Very relaxed — easy to stay for hours.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Gets packed on weekends — standing room only by midnight.",tags:["Noise/Crowd"]},
        {text:"Jukebox dominates the sound — not a talking bar late.",tags:["Noise/Crowd"]},
        {text:"One of the cheaper bars in the area.",tags:["Atmosphere & Vibe"]},
        {text:"Rivington St is busy and well-lit late.",tags:["Getting there/home"]},
        {text:"Crowd is mixed and generally good-natured.",tags:["Safety & Comfort"]},
      ],
    },
    areaActivity:["Rivington St is one of the busiest LES streets late night.","Foot traffic stays high until 3–4 am on weekends.","Multiple rideshare pickup spots on Delancey nearby."],
  },
  {
    id:"happy_ending",name:"Happy Ending",neighbourhood:"Lower East Side",type:"Bar/Lounge",
    address:"302 Broome St, Lower East Side",hours:"Open till 4 am",
    coordinates:[-73.9955,40.7166],
    tags:["Bar","Lounge","Late Night"],
    transit:{name:"Grand St B/D",tags:["Quiet at Night"],fromNYU:"Take the F to Jay St, transfer to B/D at Broadway-Lafayette (15 min)."},
    observations:{
      day:[
        {text:"Rarely opens before evening.",tags:["Atmosphere & Vibe"]},
        {text:"The tiled former spa walls give it a distinctive look.",tags:["Atmosphere & Vibe"]},
        {text:"Good for early evening cocktails before heading elsewhere.",tags:["Atmosphere & Vibe"]},
        {text:"Quieter downstairs area good for conversations.",tags:["Noise/Crowd"]},
      ],
      night:[
        {text:"Lower level gets very dark and loud after midnight.",tags:["Noise/Crowd"]},
        {text:"DJs most weekends — not a talking bar late.",tags:["Noise/Crowd"]},
        {text:"Crowd is young and fashion-conscious.",tags:["Atmosphere & Vibe"]},
        {text:"Broome St at this end is quieter for rideshares.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Canal St nearby can be chaotic late on weekends.","Area is mixed residential and bar — foot traffic varies.","Worth having a rideshare plan before you go."],
  },
  {
    id:"le_turtle",name:"Le Turtle",neighbourhood:"Lower East Side",type:"Restaurant/Bar",
    address:"177 Chrystie St, Lower East Side",hours:"Open till 11 pm",
    coordinates:[-73.9935,40.7210],
    tags:["Restaurant","Bar","French"],
    transit:{name:"2nd Ave F",tags:["Well Lit"],fromNYU:"Take the F from Jay St (10 min). 4 min walk."},
    observations:{
      day:[
        {text:"Relaxed lunch crowd — good natural light from the front windows.",tags:["Atmosphere & Vibe"]},
        {text:"Worth trying the bar menu if the dining room is full.",tags:["Atmosphere & Vibe"]},
        {text:"Staff are attentive without being intrusive.",tags:["Atmosphere & Vibe"]},
        {text:"Chrystie St is calm and easy to walk during the day.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Dinner fills up — reservations recommended.",tags:["Noise/Crowd"]},
        {text:"Noise level is moderate even when full.",tags:["Noise/Crowd"]},
        {text:"Bar area stays open after the kitchen closes.",tags:["Atmosphere & Vibe"]},
        {text:"Good for a date or small group dinner.",tags:["Atmosphere & Vibe"]},
      ],
    },
    areaActivity:["Chrystie St is quieter than the Orchard/Rivington corridor.","Sara D. Roosevelt Park is adjacent — calm but less lit at night.","Easy to get a rideshare heading uptown."],
  },

  // ── WEST VILLAGE ─────────────────────────────────────────────────────────
  {
    id:"employees_only",name:"Employees Only",neighbourhood:"West Village",type:"Cocktail Bar",
    address:"510 Hudson St, West Village",hours:"Open till 3:30 am",
    coordinates:[-74.0058,40.7330],
    tags:["Cocktail Bar","Late Night","West Village"],
    transit:{name:"Christopher St A/C/E",tags:["Well Lit","Safe"],fromNYU:"Take A/C/E from Jay St to 14th St, walk or 1 stop to Christopher St (18 min)."},
    observations:{
      day:[
        {text:"Opens in the evening — not a daytime spot.",tags:["Atmosphere & Vibe"]},
        {text:"The psychic booth at the entrance sets the tone.",tags:["Atmosphere & Vibe"]},
        {text:"Early evening is the best time to get a seat at the bar.",tags:["Noise/Crowd"]},
        {text:"Staff are some of the most knowledgeable in the city.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Busy most nights — weekend waits can be 30+ min.",tags:["Noise/Crowd"]},
        {text:"Late nights get louder but the cocktails stay excellent.",tags:["Atmosphere & Vibe"]},
        {text:"Back dining room is an option for a quieter experience.",tags:["Noise/Crowd"]},
        {text:"Hudson St is calm and residential — easy to get a cab.",tags:["Getting there/home"]},
        {text:"Crowd is mixed — regulars, tourists, industry people.",tags:["Atmosphere & Vibe"]},
      ],
    },
    areaActivity:["Hudson St is well-lit and quiet relative to other bar areas.","West Village streets are generally safe and walkable late.","Cabs and rideshares easy to find on Hudson."],
  },
  {
    id:"buvette",name:"Buvette",neighbourhood:"West Village",type:"Restaurant/Bar",
    address:"42 Grove St, West Village",hours:"Open till midnight",
    coordinates:[-74.0024,40.7335],
    tags:["Restaurant","Wine Bar","French","West Village"],
    transit:{name:"Christopher St A/C/E",tags:["Well Lit","Safe"],fromNYU:"Take A/C/E from Jay St to Christopher St (18 min). 4 min walk."},
    observations:{
      day:[
        {text:"Brunch is extremely popular — expect a wait on weekends.",tags:["Noise/Crowd"]},
        {text:"The cramped space adds to the charm for some, not for others.",tags:["Atmosphere & Vibe"]},
        {text:"Good coffee and pastries — easy to stop in quickly.",tags:["Atmosphere & Vibe"]},
        {text:"Grove St is one of the prettier blocks in the Village.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Intimate and candlelit — good for a romantic dinner.",tags:["Atmosphere & Vibe"]},
        {text:"Noise level is high when full — cosy but loud.",tags:["Noise/Crowd"]},
        {text:"Wine list is strong — staff happy to guide you through it.",tags:["Atmosphere & Vibe"]},
        {text:"Reservations essential for dinner on weekends.",tags:["Noise/Crowd"]},
      ],
    },
    areaActivity:["Grove St is residential and calm even late.","West Village is one of the safer areas to walk at night.","Limited late-night food options nearby after midnight."],
  },
  {
    id:"little_branch",name:"Little Branch",neighbourhood:"West Village",type:"Cocktail Bar",
    address:"20 7th Ave S, West Village",hours:"Open till 3 am",
    coordinates:[-74.0003,40.7333],
    tags:["Cocktail Bar","Speakeasy","Jazz","West Village"],
    transit:{name:"Christopher St A/C/E",tags:["Well Lit","Safe"],fromNYU:"A/C/E from Jay St to Christopher St (18 min). 3 min walk."},
    observations:{
      day:[
        {text:"Opens in the evening — jazz starts later.",tags:["Atmosphere & Vibe"]},
        {text:"Underground entrance gives it a genuine speakeasy feel.",tags:["Atmosphere & Vibe"]},
        {text:"Worth arriving early to get a proper seat.",tags:["Noise/Crowd"]},
        {text:"One of the most atmospheric bars in the city.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Live jazz most nights — check the schedule.",tags:["Atmosphere & Vibe"]},
        {text:"Gets very full after 10 pm — arrive before then.",tags:["Noise/Crowd"]},
        {text:"Cocktails are exceptional and staff take them seriously.",tags:["Atmosphere & Vibe"]},
        {text:"Cash preferred — bring some.",tags:["Safety & Comfort"]},
        {text:"7th Ave is busy and well-lit — easy to get home.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["7th Ave South is lively but not rowdy.","West Village is calm and walkable even after midnight.","Multiple cab and rideshare options on 7th Ave."],
  },
  {
    id:"white_horse_tavern",name:"White Horse Tavern",neighbourhood:"West Village",type:"Bar",
    address:"567 Hudson St, West Village",hours:"Open till 2 am",
    coordinates:[-74.0059,40.7342],
    tags:["Bar","Historic","West Village"],
    transit:{name:"Christopher St A/C/E",tags:["Well Lit","Safe"],fromNYU:"A/C/E from Jay St to Christopher St (18 min). 5 min walk."},
    observations:{
      day:[
        {text:"Afternoon pints in a bar that's been here since 1880.",tags:["Atmosphere & Vibe"]},
        {text:"Outdoor tables on Hudson are good when the weather cooperates.",tags:["Atmosphere & Vibe"]},
        {text:"Tourist-aware but still feels like a proper local bar.",tags:["Atmosphere & Vibe"]},
        {text:"Food is reliable pub fare — decent burger.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Gets busy but rarely overwhelming.",tags:["Noise/Crowd"]},
        {text:"Outdoor seating fills up first — arrive early.",tags:["Noise/Crowd"]},
        {text:"Crowd is mixed — locals, tourists, Village regulars.",tags:["Atmosphere & Vibe"]},
        {text:"Hudson St is calm and well-lit late.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Hudson St is one of the calmer main streets in the Village late at night.","Residential neighbourhood — noise levels stay reasonable.","Easy to walk to multiple subway lines."],
  },
  {
    id:"the_village_vanguard",name:"Village Vanguard",neighbourhood:"West Village",type:"Jazz Club/Bar",
    address:"178 7th Ave S, West Village",hours:"Shows from 8 pm",
    coordinates:[-74.0006,40.7367],
    tags:["Jazz","Bar","West Village","Live Music"],
    transit:{name:"14th St A/C/E or 1/2/3",tags:["Well Lit","Busy"],fromNYU:"A/C/E from Jay St to 14th St (16 min). 5 min walk south."},
    observations:{
      day:[
        {text:"Closed during the day — evening shows only.",tags:["Atmosphere & Vibe"]},
        {text:"Worth booking in advance — sets sell out.",tags:["Noise/Crowd"]},
        {text:"Two sets most nights — the later one is often looser.",tags:["Atmosphere & Vibe"]},
        {text:"The basement space has incredible acoustics.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Best jazz venue in the city — the real thing.",tags:["Atmosphere & Vibe"]},
        {text:"Quiet during performances — no talking expected.",tags:["Noise/Crowd"]},
        {text:"Minimum charge applies — budget accordingly.",tags:["Safety & Comfort"]},
        {text:"7th Ave is busy — easy to get a cab after the show.",tags:["Getting there/home"]},
        {text:"The late set (around 10:30) draws a more serious crowd.",tags:["Atmosphere & Vibe"]},
      ],
    },
    areaActivity:["7th Ave is well-lit and active most evenings.","14th St nearby has good late-night food options.","Area is safe and well-transited."],
  },
  {
    id:"fedora",name:"Fedora",neighbourhood:"West Village",type:"Restaurant/Bar",
    address:"239 W 4th St, West Village",hours:"Open till midnight",
    coordinates:[-74.0027,40.7320],
    tags:["Restaurant","Bar","West Village"],
    transit:{name:"Christopher St A/C/E",tags:["Well Lit","Safe"],fromNYU:"A/C/E to Christopher St (18 min). 4 min walk."},
    observations:{
      day:[
        {text:"Brunch popular — the Bloody Marys are worth it.",tags:["Atmosphere & Vibe"]},
        {text:"Relaxed pace during the day — good for a long lunch.",tags:["Noise/Crowd"]},
        {text:"The basement bar is open from early evening.",tags:["Atmosphere & Vibe"]},
        {text:"W 4th is a lively but manageable street.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Dinner fills up — reservations recommended.",tags:["Noise/Crowd"]},
        {text:"Bar downstairs stays open after the kitchen — a solid late option.",tags:["Atmosphere & Vibe"]},
        {text:"Crowd is local West Village — low-key and friendly.",tags:["Atmosphere & Vibe"]},
        {text:"Moderate noise level even when full.",tags:["Noise/Crowd"]},
      ],
    },
    areaActivity:["W 4th is one of the livelier West Village streets.","Well-lit and heavily foot-trafficked in the evening.","Sheridan Square nearby for transit."],
  },
  {
    id:"the_half_king",name:"The Half King",neighbourhood:"West Village",type:"Bar/Restaurant",
    address:"505 W 23rd St, West Village",hours:"Open till 2 am",
    coordinates:[-74.0065,40.7486],
    tags:["Bar","Restaurant","Chelsea","Literary"],
    transit:{name:"23rd St C/E",tags:["Well Lit"],fromNYU:"A/C/E from Jay St to 23rd St (20 min). 3 min walk."},
    observations:{
      day:[
        {text:"Literary bar with a relaxed afternoon crowd.",tags:["Atmosphere & Vibe"]},
        {text:"Good food — the burger is a reliable choice.",tags:["Atmosphere & Vibe"]},
        {text:"Outdoor patio in good weather is excellent.",tags:["Atmosphere & Vibe"]},
        {text:"Reading series and events most weeks — check their calendar.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Busier on weekends but never overwhelming.",tags:["Noise/Crowd"]},
        {text:"Good for conversations — the noise level stays reasonable.",tags:["Noise/Crowd"]},
        {text:"Gallery crowd and writers mixed with regulars.",tags:["Atmosphere & Vibe"]},
        {text:"23rd St is well-connected — easy to get home late.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["23rd St corridor has a lot of evening foot traffic.","Chelsea is generally safe and well-lit at night.","Multiple transit options nearby."],
  },
  {
    id:"don_the_beachcomber",name:"Mother of Pearl",neighbourhood:"West Village",type:"Tiki Bar",
    address:"95 Greenwich Ave, West Village",hours:"Open till 2 am",
    coordinates:[-74.0007,40.7358],
    tags:["Tiki Bar","Cocktails","West Village"],
    transit:{name:"14th St A/C/E",tags:["Well Lit","Busy"],fromNYU:"A/C/E from Jay St to 14th St (16 min). 5 min walk."},
    observations:{
      day:[
        {text:"Opens mid-afternoon — good for an early tropical drink.",tags:["Atmosphere & Vibe"]},
        {text:"Campy decor makes it fun at any time of day.",tags:["Atmosphere & Vibe"]},
        {text:"Happy hour deals worth knowing about.",tags:["Atmosphere & Vibe"]},
        {text:"Staff are friendly and enthusiastic about the menu.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Gets lively after 9 pm — fun crowd.",tags:["Noise/Crowd"]},
        {text:"Loud and celebratory — not a quiet night out.",tags:["Noise/Crowd"]},
        {text:"Great for groups and birthdays.",tags:["Atmosphere & Vibe"]},
        {text:"Greenwich Ave is well-lit and easy to navigate late.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Greenwich Ave is a busy Village thoroughfare.","Well-lit and active most evenings.","Multiple transit lines converge nearby."],
  },

  // ── WILLIAMSBURG ─────────────────────────────────────────────────────────
  {
    id:"maison_premiere",name:"Maison Premiere",neighbourhood:"Williamsburg",type:"Cocktail Bar/Restaurant",
    address:"298 Bedford Ave, Williamsburg",hours:"Open till 2 am",
    coordinates:[-73.9573,40.7146],
    tags:["Cocktail Bar","Oysters","Williamsburg"],
    transit:{name:"Bedford Ave L",tags:["Well Lit","Busy"],fromNYU:"Take the F to Jay St, L to Bedford Ave (20 min)."},
    observations:{
      day:[
        {text:"Garden is one of the best outdoor drinking spots in Brooklyn.",tags:["Atmosphere & Vibe"]},
        {text:"Afternoon absinthe service is a ritual worth doing.",tags:["Atmosphere & Vibe"]},
        {text:"Oyster happy hour is excellent value.",tags:["Atmosphere & Vibe"]},
        {text:"Bedford Ave is busy but the interior garden feels removed from it.",tags:["Noise/Crowd"]},
      ],
      night:[
        {text:"Very popular — waits are common on weekend nights.",tags:["Noise/Crowd"]},
        {text:"Garden fills up first — ask to be seated there if possible.",tags:["Atmosphere & Vibe"]},
        {text:"Cocktails are serious and excellent.",tags:["Atmosphere & Vibe"]},
        {text:"Bedford Ave is busy late — L train easy to catch nearby.",tags:["Getting there/home"]},
        {text:"Crowd is Williamsburg creative — tends to be good-natured.",tags:["Atmosphere & Vibe"]},
      ],
    },
    areaActivity:["Bedford Ave is one of the busiest streets in Williamsburg at night.","L train runs frequently until late.","Lively block with multiple bars and restaurants nearby."],
  },
  {
    id:"ides_bar",name:"Ides Bar",neighbourhood:"Williamsburg",type:"Rooftop Bar",
    address:"80 Wythe Ave, Williamsburg",hours:"Open till 1 am",
    coordinates:[-73.9595,40.7218],
    tags:["Rooftop","Bar","Views","Williamsburg"],
    transit:{name:"Bedford Ave L",tags:["Well Lit","Busy"],fromNYU:"F to Jay St, L to Bedford Ave (20 min). 10 min walk."},
    observations:{
      day:[
        {text:"Wythe Hotel rooftop — Manhattan skyline views are the main event.",tags:["Atmosphere & Vibe"]},
        {text:"Quieter on weekday afternoons — easier to get a spot.",tags:["Noise/Crowd"]},
        {text:"Good cocktails at hotel prices.",tags:["Atmosphere & Vibe"]},
        {text:"Worth it for the views even if you only have one drink.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Very busy on weekend nights — arrive before 8 pm.",tags:["Noise/Crowd"]},
        {text:"Skyline views at night are genuinely impressive.",tags:["Atmosphere & Vibe"]},
        {text:"Gets cold in autumn and winter — dress accordingly.",tags:["Safety & Comfort"]},
        {text:"Wythe Ave is well-lit and busy — easy to get a rideshare.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Wythe Ave is active and well-lit most evenings.","Multiple bars and restaurants on the block.","L train a 10 min walk — rideshares often quicker late."],
  },
  {
    id:"hotel_delmano",name:"Hotel Delmano",neighbourhood:"Williamsburg",type:"Cocktail Bar",
    address:"82 Berry St, Williamsburg",hours:"Open till 2 am",
    coordinates:[-73.9616,40.7186],
    tags:["Cocktail Bar","Williamsburg","Classic"],
    transit:{name:"Bedford Ave L",tags:["Well Lit"],fromNYU:"F to Jay St, L to Bedford Ave (20 min). 8 min walk."},
    observations:{
      day:[
        {text:"Opens in the late afternoon — sets the mood for evening.",tags:["Atmosphere & Vibe"]},
        {text:"Dark wood and mirrors give it a classic cocktail bar feel.",tags:["Atmosphere & Vibe"]},
        {text:"Good for an early evening drink before dinner nearby.",tags:["Atmosphere & Vibe"]},
        {text:"Berry St is calm and residential.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Fills up steadily after 9 pm without getting overwhelming.",tags:["Noise/Crowd"]},
        {text:"Intimate atmosphere holds even when busy.",tags:["Atmosphere & Vibe"]},
        {text:"Cocktail menu changes seasonally — staff know it well.",tags:["Atmosphere & Vibe"]},
        {text:"Quieter than Bedford Ave bars — a calmer Williamsburg option.",tags:["Noise/Crowd"]},
      ],
    },
    areaActivity:["Berry St is quieter than Bedford Ave — more residential.","Good option if you want Williamsburg without the full-crowd energy.","L train reachable in 8 min on foot."],
  },
  {
    id:"the_flying_pan",name:"The William Vale",neighbourhood:"Williamsburg",type:"Rooftop Bar",
    address:"111 N 12th St, Williamsburg",hours:"Open till midnight",
    coordinates:[-73.9596,40.7228],
    tags:["Rooftop","Bar","Views","Williamsburg"],
    transit:{name:"Bedford Ave L",tags:["Well Lit","Busy"],fromNYU:"F to Jay St, L to Bedford Ave (20 min). 12 min walk."},
    observations:{
      day:[
        {text:"Sweeping Manhattan and East River views on a clear day.",tags:["Atmosphere & Vibe"]},
        {text:"Pool area in season — check their website for access.",tags:["Atmosphere & Vibe"]},
        {text:"Less crowded on weekday afternoons.",tags:["Noise/Crowd"]},
        {text:"Hotel bar pricing — not a cheap night.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"One of the best skyline views in Brooklyn at night.",tags:["Atmosphere & Vibe"]},
        {text:"Busy on weekends — reservations or early arrival recommended.",tags:["Noise/Crowd"]},
        {text:"Wind exposure on the rooftop — bring a layer.",tags:["Safety & Comfort"]},
        {text:"Rideshares easy from N 12th St.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["North Williamsburg waterfront area is active and well-developed.","N 12th St is busy with venue foot traffic evenings.","L train is the most reliable transit back to Manhattan."],
  },
  {
    id:"marlow_and_sons",name:"Marlow & Sons",neighbourhood:"Williamsburg",type:"Restaurant/Bar",
    address:"81 Broadway, Williamsburg",hours:"Open till midnight",
    coordinates:[-73.9643,40.7094],
    tags:["Restaurant","Bar","Williamsburg","Neighbourhood"],
    transit:{name:"Marcy Ave J/M/Z",tags:["Quiet at Night"],fromNYU:"F to Jay St, J/M/Z to Marcy Ave (18 min). 5 min walk."},
    observations:{
      day:[
        {text:"Neighbourhood brunch staple — expect a line on weekends.",tags:["Noise/Crowd"]},
        {text:"Counter seating at the bar is walk-in and good for solo visits.",tags:["Safety & Comfort"]},
        {text:"Coffee is excellent — often used as a cafe in the morning.",tags:["Atmosphere & Vibe"]},
        {text:"South Williamsburg vibe — less hectic than the Bedford Ave area.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Dinner is quieter than the brunch rush — easier to get a table.",tags:["Noise/Crowd"]},
        {text:"Small plates and oysters at the bar work well for two.",tags:["Atmosphere & Vibe"]},
        {text:"Intimate and low-lit — good for a date.",tags:["Atmosphere & Vibe"]},
        {text:"Broadway in S. Williamsburg is quieter at night than the main strip.",tags:["Safety & Comfort"]},
      ],
    },
    areaActivity:["Broadway in south Williamsburg is quieter than north.",,"J/M/Z trains less frequent late — check schedule.","Area is safe but transit options thin after midnight."],
  },
  {
    id:"nights_and_weekends",name:"Nights & Weekends",neighbourhood:"Williamsburg",type:"Bar",
    address:"197 Grand St, Williamsburg",hours:"Open till 3 am",
    coordinates:[-73.9635,40.7132],
    tags:["Bar","Late Night","Williamsburg"],
    transit:{name:"Grand St L",tags:["Quiet at Night"],fromNYU:"F to Jay St, L to Grand St (22 min). 3 min walk."},
    observations:{
      day:[
        {text:"Rarely open before evening — a night bar by identity.",tags:["Atmosphere & Vibe"]},
        {text:"Good soundtrack and unpretentious vibe.",tags:["Atmosphere & Vibe"]},
        {text:"Cheap and cheerful — no fuss.",tags:["Atmosphere & Vibe"]},
        {text:"Grand St is quieter than Bedford.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Packed late — one of the go-to Williamsburg late spots.",tags:["Noise/Crowd"]},
        {text:"Cheap drinks and a good crowd.",tags:["Atmosphere & Vibe"]},
        {text:"Loud after midnight — no conversations.",tags:["Noise/Crowd"]},
        {text:"Grand St L is a short walk and runs late.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Grand St corridor is busy late on weekends.","Quieter than the Bedford Ave strip but still active.","L train at Grand St is the easiest way home."],
  },
  {
    id:"st_anselm",name:"St. Anselm",neighbourhood:"Williamsburg",type:"Restaurant/Bar",
    address:"355 Metropolitan Ave, Williamsburg",hours:"Open till 11 pm",
    coordinates:[-73.9571,40.7130],
    tags:["Restaurant","Bar","Steakhouse","Williamsburg"],
    transit:{name:"Lorimer St L/G",tags:["Well Lit"],fromNYU:"F to Jay St, L to Lorimer St (22 min). 5 min walk."},
    observations:{
      day:[
        {text:"No lunch service — dinner only.",tags:["Atmosphere & Vibe"]},
        {text:"Bar area great for a drink before your table is ready.",tags:["Atmosphere & Vibe"]},
        {text:"One of the best steaks in Brooklyn — worth the splurge.",tags:["Atmosphere & Vibe"]},
        {text:"Metropolitan Ave is calm and walkable.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Dinner gets loud in a good way — buzzy and social.",tags:["Noise/Crowd"]},
        {text:"Walk-in bar seats are the move if you can't get a reservation.",tags:["Atmosphere & Vibe"]},
        {text:"Reservations essential on weekends.",tags:["Noise/Crowd"]},
        {text:"L train nearby makes it easy to get home.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Metropolitan Ave has a mix of restaurants and bars.","Quieter than the waterfront but still lively on weekends.","Lorimer St L/G is nearby for transit."],
  },
  {
    id:"pearl_s_bar",name:"Pearl's Social and Billy Club",neighbourhood:"Williamsburg",type:"Dive Bar",
    address:"40 Saint Nicholas Ave, Williamsburg",hours:"Open till 4 am",
    coordinates:[-73.9527,40.7148],
    tags:["Dive Bar","Late Night","Williamsburg"],
    transit:{name:"Montrose Ave L",tags:["Quiet at Night"],fromNYU:"F to Jay St, L to Montrose Ave (25 min). 5 min walk."},
    observations:{
      day:[
        {text:"Classic dive bar — unpretentious and cheap.",tags:["Atmosphere & Vibe"]},
        {text:"Regular crowd of local Williamsburg people.",tags:["Atmosphere & Vibe"]},
        {text:"Pool table and jukebox — good for an afternoon.",tags:["Atmosphere & Vibe"]},
        {text:"Quiet side of Williamsburg — calmer neighbourhood.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Gets busier after midnight when other places close.",tags:["Noise/Crowd"]},
        {text:"One of the few reliably open 4 am bars in Brooklyn.",tags:["Atmosphere & Vibe"]},
        {text:"Crowd gets looser very late — be aware of the energy.",tags:["Safety & Comfort"]},
        {text:"Montrose Ave L is the closest transit — runs infrequently late.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Side street — quieter than the main Williamsburg drags.","Transit options thin very late — plan your rideshare.","Neighbourhood is calm but industrial in character."],
  },
  {
    id:"reynard",name:"Reynard",neighbourhood:"Williamsburg",type:"Restaurant/Bar",
    address:"80 Wythe Ave, Williamsburg",hours:"Open till 11 pm",
    coordinates:[-73.9595,40.7213],
    tags:["Restaurant","Bar","Williamsburg","Hotel"],
    transit:{name:"Bedford Ave L",tags:["Well Lit","Busy"],fromNYU:"F to Jay St, L to Bedford Ave (20 min). 10 min walk."},
    observations:{
      day:[
        {text:"Wythe Hotel restaurant — good for a relaxed weekend brunch.",tags:["Atmosphere & Vibe"]},
        {text:"Airy space with good natural light.",tags:["Atmosphere & Vibe"]},
        {text:"Bar is open through the afternoon — good coffee too.",tags:["Atmosphere & Vibe"]},
        {text:"Polished but not stiff — comfortable for a long meal.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Dinner is solid — the wood-fired dishes are the move.",tags:["Atmosphere & Vibe"]},
        {text:"Buzz from the hotel crowd but not overwhelming.",tags:["Noise/Crowd"]},
        {text:"Bar area good for drinks without a meal reservation.",tags:["Atmosphere & Vibe"]},
        {text:"Wythe Ave is well-connected — easy rideshare.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Wythe Ave is one of the busiest streets in N. Williamsburg.","Area is well-lit and active most evenings.","L train a 10 min walk — rideshares often faster late."],
  },

  // ── DOWNTOWN BROOKLYN / COBBLE HILL ──────────────────────────────────────
  {
    id:"clover_club",name:"Clover Club",neighbourhood:"Cobble Hill",type:"Cocktail Bar",
    address:"210 Smith St, Cobble Hill",hours:"Open till midnight",
    coordinates:[-73.9944,40.6843],
    tags:["Cocktail Bar","Brooklyn","Cobble Hill"],
    transit:{name:"Bergen St F/G",tags:["Well Lit","Safe"],fromNYU:"Take F from Jay St (2 stops, 5 min). Exit Bergen St, 8 min walk."},
    observations:{
      day:[
        {text:"Opens in the late afternoon — a good early evening cocktail spot.",tags:["Atmosphere & Vibe"]},
        {text:"One of the best cocktail bars in Brooklyn — elegant without being stuffy.",tags:["Atmosphere & Vibe"]},
        {text:"Quiet enough to have a proper conversation.",tags:["Noise/Crowd"]},
        {text:"Smith St is walkable and safe.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Gets busy but rarely overcrowded — the space is well-designed.",tags:["Noise/Crowd"]},
        {text:"Seasonal cocktail menu is excellent.",tags:["Atmosphere & Vibe"]},
        {text:"Good for dates and small group evenings.",tags:["Atmosphere & Vibe"]},
        {text:"Smith St is quiet enough to walk at night.",tags:["Safety & Comfort"]},
        {text:"F/G trains close — easy to get home.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Smith St is a busy restaurant and bar corridor.","Cobble Hill is quiet and residential — evenings are calm.","F and G trains are very close."],
  },
  {
    id:"frankies_457",name:"Frankies 457",neighbourhood:"Carroll Gardens",type:"Restaurant/Bar",
    address:"457 Court St, Carroll Gardens",hours:"Open till 11 pm",
    coordinates:[-73.9994,40.6787],
    tags:["Restaurant","Bar","Italian","Carroll Gardens"],
    transit:{name:"Smith-9th St F/G",tags:["Well Lit"],fromNYU:"Take F from Jay St to Smith-9th St (8 min). 10 min walk."},
    observations:{
      day:[
        {text:"A neighbourhood institution — brunch queue is worth it.",tags:["Noise/Crowd"]},
        {text:"Garden out back is one of the best in Brooklyn.",tags:["Atmosphere & Vibe"]},
        {text:"Relaxed pace — good for a long afternoon meal.",tags:["Atmosphere & Vibe"]},
        {text:"Court St is calm and very residential.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Dinner fills the room — intimate and warm.",tags:["Atmosphere & Vibe"]},
        {text:"Reservations recommended for weekends.",tags:["Noise/Crowd"]},
        {text:"The garden is magical on a warm night.",tags:["Atmosphere & Vibe"]},
        {text:"Carroll Gardens is very quiet late — bring your own plan for after.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Carroll Gardens is one of the quieter Brooklyn neighbourhoods at night.","Court St has some bars and restaurants but area winds down by midnight.","F/G trains a short walk."],
  },
  {
    id:"dean_st_wines",name:"June Wine Bar",neighbourhood:"Cobble Hill",type:"Wine Bar",
    address:"231 Court St, Cobble Hill",hours:"Open till midnight",
    coordinates:[-73.9944,40.6854],
    tags:["Wine Bar","Cobble Hill","Natural Wine"],
    transit:{name:"Bergen St F/G",tags:["Well Lit","Safe"],fromNYU:"F from Jay St to Bergen St (5 min). 5 min walk."},
    observations:{
      day:[
        {text:"Relaxed afternoon wine bar — excellent for a slow afternoon.",tags:["Atmosphere & Vibe"]},
        {text:"Natural wine list is carefully curated.",tags:["Atmosphere & Vibe"]},
        {text:"Small plates are worth ordering.",tags:["Atmosphere & Vibe"]},
        {text:"Quiet neighbourhood street.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Gets busy in the early evening — neighbourhood crowd.",tags:["Noise/Crowd"]},
        {text:"Intimate and low-key — conversation-friendly.",tags:["Noise/Crowd"]},
        {text:"Good option if you want a quieter Brooklyn night.",tags:["Atmosphere & Vibe"]},
        {text:"Court St is calm — easy to walk or get a rideshare.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Court St is one of the calmer bar streets in Brooklyn.","Cobble Hill is residential — very quiet after midnight.","F/G transit is reliable and nearby."],
  },
  {
    id:"butter_and_scotch",name:"Butter & Scotch",neighbourhood:"Crown Heights",type:"Bar/Bakery",
    address:"818 Franklin Ave, Crown Heights",hours:"Open till midnight",
    coordinates:[-73.9557,40.6686],
    tags:["Bar","Desserts","Crown Heights"],
    transit:{name:"Franklin Ave C/S",tags:["Well Lit"],fromNYU:"F to Jay St, A/C to Franklin Ave (18 min). 1 min walk."},
    observations:{
      day:[
        {text:"Cocktails and desserts — the combination works better than it sounds.",tags:["Atmosphere & Vibe"]},
        {text:"Brunch here is genuinely fun — boozy milkshakes are real.",tags:["Atmosphere & Vibe"]},
        {text:"Franklin Ave has developed a lot — lively neighbourhood vibe.",tags:["Atmosphere & Vibe"]},
        {text:"Relaxed and welcoming crowd.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Gets busy on weekends — worth arriving before 8 pm.",tags:["Noise/Crowd"]},
        {text:"Fun and festive atmosphere — good for groups.",tags:["Atmosphere & Vibe"]},
        {text:"Franklin Ave is well-lit and walkable.",tags:["Safety & Comfort"]},
        {text:"C train is very close — easy transit.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Franklin Ave is a growing bar and restaurant corridor.","Crown Heights has gentrified quickly — area is active and well-lit.","C train is steps away."],
  },
  {
    id:"nights_watch_bk",name:"Berg'n",neighbourhood:"Crown Heights",type:"Bar/Food Hall",
    address:"899 Bergen St, Crown Heights",hours:"Open till 2 am",
    coordinates:[-73.9583,40.6760],
    tags:["Bar","Food Hall","Crown Heights","Group"],
    transit:{name:"Bergen St 2/3",tags:["Well Lit","Busy"],fromNYU:"F to Jay St, 2/3 to Bergen St (12 min). 2 min walk."},
    observations:{
      day:[
        {text:"Food hall format — multiple vendors, easy to please a group.",tags:["Atmosphere & Vibe"]},
        {text:"Long communal tables work well for larger groups.",tags:["Noise/Crowd"]},
        {text:"Relaxed daytime atmosphere — good for a casual lunch.",tags:["Atmosphere & Vibe"]},
        {text:"Bergen St is busy and well-serviced by transit.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Gets busy and loud on weekend nights.",tags:["Noise/Crowd"]},
        {text:"Good for groups who can't agree on a single restaurant.",tags:["Atmosphere & Vibe"]},
        {text:"Draft beer selection is solid.",tags:["Atmosphere & Vibe"]},
        {text:"2/3 train is steps away — excellent transit.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Bergen St is well-lit and busy in the evenings.","2/3 subway makes this one of the best-connected Brooklyn venues.","Crown Heights neighbourhood is active and mixed."],
  },
  {
    id:"hinterlands",name:"Hinterlands",neighbourhood:"Downtown Brooklyn",type:"Bar",
    address:"469 Atlantic Ave, Downtown Brooklyn",hours:"Open till 2 am",
    coordinates:[-73.9848,40.6849],
    tags:["Bar","Brooklyn","Downtown Brooklyn"],
    transit:{name:"Atlantic Ave–Barclays A/C/G/2/3/4/5",tags:["Well Lit","Busy","Major Hub"],fromNYU:"F to Jay St, A/C to Atlantic Ave (8 min). 3 min walk."},
    observations:{
      day:[
        {text:"Low-key bar on a busy Atlantic Ave block.",tags:["Atmosphere & Vibe"]},
        {text:"Good for an afternoon pint without fuss.",tags:["Atmosphere & Vibe"]},
        {text:"Mixed local crowd.",tags:["Noise/Crowd"]},
        {text:"Atlantic Ave has everything — very central.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Busier on weekends — never uncomfortably packed.",tags:["Noise/Crowd"]},
        {text:"Good neighbourhood bar without the tourist overlay.",tags:["Atmosphere & Vibe"]},
        {text:"Atlantic-Barclays is one of the best-transited spots in Brooklyn.",tags:["Getting there/home"]},
        {text:"Area is very busy and well-lit.",tags:["Safety & Comfort"]},
      ],
    },
    areaActivity:["Atlantic Ave is one of the busiest Brooklyn corridors.","Barclays Center events can significantly increase foot traffic.","Best-connected transit hub in Brooklyn."],
  },
  {
    id:"the_osprey",name:"The Osprey",neighbourhood:"Downtown Brooklyn",type:"Bar/Restaurant",
    address:"333 Adams St, Downtown Brooklyn",hours:"Open till midnight",
    coordinates:[-73.9898,40.6931],
    tags:["Bar","Restaurant","Hotel","Downtown Brooklyn"],
    transit:{name:"Jay St–MetroTech A/C/F/R",tags:["Well Lit","Busy"],fromNYU:"5 min walk from NYU Brooklyn campus."},
    observations:{
      day:[
        {text:"1 Hotel Brooklyn Bridge bar — harbour views are excellent.",tags:["Atmosphere & Vibe"]},
        {text:"Good coffee and brunch in the hotel setting.",tags:["Atmosphere & Vibe"]},
        {text:"Rooftop pool terrace in season.",tags:["Atmosphere & Vibe"]},
        {text:"Polished hotel vibe — prices reflect that.",tags:["Atmosphere & Vibe"]},
      ],
      night:[
        {text:"Views of the bridge and Manhattan skyline at night are worth it.",tags:["Atmosphere & Vibe"]},
        {text:"Quieter than Manhattan hotel bars — less tourist saturation.",tags:["Noise/Crowd"]},
        {text:"Good cocktails, attentive service.",tags:["Atmosphere & Vibe"]},
        {text:"Adams St is calm — Jay St subway very close.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["DUMBO/Downtown Brooklyn border — beautiful area to walk at night.","Brooklyn Bridge Park is steps away.","Jay St transit hub makes this very accessible."],
  },
  {
    id:"grand_army",name:"Grand Army",neighbourhood:"Downtown Brooklyn",type:"Bar/Restaurant",
    address:"336 State St, Downtown Brooklyn",hours:"Open till midnight",
    coordinates:[-73.9878,40.6876],
    tags:["Bar","Oysters","Downtown Brooklyn"],
    transit:{name:"Atlantic Ave–Barclays A/C/G/2/3",tags:["Well Lit","Busy"],fromNYU:"F to Jay St, A/C to Atlantic Ave (8 min). 4 min walk."},
    observations:{
      day:[
        {text:"Oyster bar and cocktails — excellent quality for the area.",tags:["Atmosphere & Vibe"]},
        {text:"Good for a long lunch — the raw bar is the star.",tags:["Atmosphere & Vibe"]},
        {text:"Neighbourhood crowd at lunch — calm and unpretentious.",tags:["Noise/Crowd"]},
        {text:"State St is quieter than Atlantic Ave.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Good pre-Barclays or post-dinner bar.",tags:["Atmosphere & Vibe"]},
        {text:"Busy on weekends — worth making a reservation.",tags:["Noise/Crowd"]},
        {text:"Cocktail programme is strong.",tags:["Atmosphere & Vibe"]},
        {text:"Atlantic Ave transit hub is 4 min walk.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["State St is calm but close to the busy Atlantic Ave hub.","Barclays Center events affect foot traffic — check the schedule.","Multiple transit lines very close."],
  },
  {
    id:"colonie",name:"Colonie",neighbourhood:"Brooklyn Heights",type:"Restaurant/Bar",
    address:"127 Atlantic Ave, Brooklyn Heights",hours:"Open till 11 pm",
    coordinates:[-73.9942,40.6889],
    tags:["Restaurant","Bar","Brooklyn Heights"],
    transit:{name:"Borough Hall 2/3/4/5/R",tags:["Well Lit","Busy"],fromNYU:"F to Jay St, 2/3 to Borough Hall (5 min). 8 min walk."},
    observations:{
      day:[
        {text:"Relaxed weekend brunch — one of the better ones in the area.",tags:["Noise/Crowd"]},
        {text:"Feels like a proper neighbourhood restaurant.",tags:["Atmosphere & Vibe"]},
        {text:"Atlantic Ave is active and easy to walk.",tags:["Safety & Comfort"]},
        {text:"Bar area good for solo dining.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Intimate dinner atmosphere — good for a date.",tags:["Atmosphere & Vibe"]},
        {text:"Noise level stays manageable even when full.",tags:["Noise/Crowd"]},
        {text:"Wine list is well-chosen.",tags:["Atmosphere & Vibe"]},
        {text:"Borough Hall transit is very close.",tags:["Getting there/home"]},
      ],
    },
    areaActivity:["Atlantic Ave has a string of good restaurants.","Brooklyn Heights is one of the safest neighbourhoods in the borough.","Multiple subway lines at Borough Hall."],
  },
  {
    id:"popina",name:"Popina",neighbourhood:"Columbia Street Waterfront",type:"Restaurant/Bar",
    address:"127 Columbia St, Columbia Street Waterfront",hours:"Open till 11 pm",
    coordinates:[-74.0045,40.6823],
    tags:["Restaurant","Bar","Waterfront","Brooklyn"],
    transit:{name:"Smith-9th St F/G",tags:["Quiet","Residential"],fromNYU:"F from Jay St to Smith-9th St (8 min). 12 min walk or short rideshare."},
    observations:{
      day:[
        {text:"Low-key waterfront restaurant — excellent for a slow weekend lunch.",tags:["Atmosphere & Vibe"]},
        {text:"Outdoor seating with harbour views.",tags:["Atmosphere & Vibe"]},
        {text:"Very neighbourhood — unfussy and welcoming.",tags:["Atmosphere & Vibe"]},
        {text:"Columbia St corridor is quiet and residential.",tags:["Safety & Comfort"]},
      ],
      night:[
        {text:"Dinner is intimate and excellent quality.",tags:["Atmosphere & Vibe"]},
        {text:"Quieter neighbourhood — a good alternative to busier areas.",tags:["Noise/Crowd"]},
        {text:"Worth having a rideshare plan — transit is a walk.",tags:["Getting there/home"]},
        {text:"Area is calm and safe but not very active late.",tags:["Safety & Comfort"]},
      ],
    },
    areaActivity:["Columbia Street Waterfront is one of the calmer Brooklyn areas.","Very residential — area winds down after dinner service.","Plan transport in advance — transit options limited."],
  },
];

// ── EXPANDED VENUES (Part H) ─────────────────────────────────────────────────
// Builder: terse rows -> full place records.
// Row fields: [id, name, neigh, borough, type, addr, hours, archetype, transitLine]
const SIGNAL_BANK = {
  cocktail_bar: [
    {t:"Bartenders here actually listen — said 'something amaro-forward' and got something perfect.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Lighting is low but the bar itself is well lit, which I appreciate.",g:["Safety & Comfort"],d:"night"},
    {t:"Came solo on a Tuesday and felt completely fine reading at the bar.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Drinks are not cheap but they're meticulous — slow sipping is the move.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Wait can be 30+ on weekends — they take your number which is nice.",g:["Noise/Crowd"],d:"night"},
    {t:"Easy to get a Lyft right at the corner after.",g:["Getting there/home"],d:"night"},
    {t:"Bathrooms single-stall and clean.",g:["Safety & Comfort"],d:"night"},
    {t:"Crowd is dressed up but not stuffy.",g:["Atmosphere & Vibe"],d:"night"},
  ],
  dive_bar: [
    {t:"Cheap drinks, sticky floors, exactly what's on the tin.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Pool table free most weeknights — fun solo or in a group.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Loud after 11 — don't come if you want to talk.",g:["Noise/Crowd"],d:"night"},
    {t:"Bouncer at the door on weekends, which honestly I appreciate.",g:["Safety & Comfort"],d:"night"},
    {t:"Bathroom line gets long but the line is friendly.",g:["Safety & Comfort"],d:"night"},
    {t:"I've been here many times solo and never felt out of place.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Fluorescent enough outside that the walk to the train is fine.",g:["Getting there/home"],d:"night"},
  ],
  club: [
    {t:"The line moves but it's a line — get there before midnight.",g:["Noise/Crowd"],d:"night"},
    {t:"Coat check is real and worth it — don't carry your stuff around.",g:["Safety & Comfort"],d:"night"},
    {t:"Music is loud enough that you can't hold a conversation, plan accordingly.",g:["Noise/Crowd"],d:"night"},
    {t:"Crowd skews mid-20s, dressed for it, generally respectful.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Bouncers paid attention when a guy was being weird — they handled it.",g:["Safety & Comfort"],d:"night"},
    {t:"Cab line forms outside; rideshares cluster a block over.",g:["Getting there/home"],d:"night"},
    {t:"Bathroom attendants are sweet, bring small bills.",g:["Safety & Comfort"],d:"night"},
  ],
  restaurant: [
    {t:"Lunch service is calm and the food is the same as dinner — better deal.",g:["Atmosphere & Vibe"],d:"day"},
    {t:"Bar seating welcomes solo diners, no weird looks.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Reservations needed Thu–Sat, walk-in fine other nights.",g:["Noise/Crowd"],d:"night"},
    {t:"Acoustics are good — tables aren't on top of each other.",g:["Noise/Crowd"],d:"night"},
    {t:"Servers attentive without hovering.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Streets around here well-lit at dinner hours.",g:["Safety & Comfort"],d:"night"},
    {t:"Bathroom is upstairs which can be a wait — go early.",g:["Safety & Comfort"],d:"night"},
  ],
  cafe: [
    {t:"Wifi is real and outlets are plentiful — actual remote-work spot.",g:["Atmosphere & Vibe"],d:"day"},
    {t:"Easy to camp here for two hours without getting side-eye.",g:["Atmosphere & Vibe"],d:"day"},
    {t:"Pastries go fast — by 11 the case is half empty.",g:["Atmosphere & Vibe"],d:"day"},
    {t:"Quiet in the morning, picks up around lunch.",g:["Noise/Crowd"],d:"day"},
    {t:"Bathroom requires a key — staff is nice about it.",g:["Safety & Comfort"],d:"day"},
    {t:"Counter staff lets me leave my laptop while I run out — that kind of place.",g:["Safety & Comfort"],d:"day"},
  ],
  wine_bar: [
    {t:"By-the-glass list is short and good — they'll pour tastes.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Lights low but not so low that I'd worry walking out alone.",g:["Safety & Comfort"],d:"night"},
    {t:"Good for a date or a solo glass — not loud.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Snacks beyond the cliché — actual food.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Cabs easy to get on the corner.",g:["Getting there/home"],d:"night"},
    {t:"Tends to fill by 8 on weekends.",g:["Noise/Crowd"],d:"night"},
  ],
  rooftop: [
    {t:"Views are real, get there before sunset on a weekend.",g:["Atmosphere & Vibe"],d:"day"},
    {t:"Wind picks up after 10 — bring a layer even in summer.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Drinks markup is steep but you're paying for the view.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Crowd skews tourist on weekends, locals on weeknights.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Elevator line down can get long around closing — pace yourself.",g:["Noise/Crowd"],d:"night"},
    {t:"Lobby and street outside well-lit on the way out.",g:["Safety & Comfort"],d:"night"},
  ],
  music_venue: [
    {t:"Sound is genuinely good and the room is the right size.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Front-of-stage gets crowded — the back has space and visibility.",g:["Noise/Crowd"],d:"night"},
    {t:"Security at the door pays attention.",g:["Safety & Comfort"],d:"night"},
    {t:"Came alone for a show and was completely fine.",g:["Safety & Comfort"],d:"night"},
    {t:"Ear plugs at the bar for free or cheap — take them.",g:["Safety & Comfort"],d:"night"},
    {t:"Walk to the train is busy enough to feel okay after.",g:["Getting there/home"],d:"night"},
  ],
  bistro: [
    {t:"Service is French-warm — they let you linger.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Wine list is short and considered.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Quiet enough at lunch to take a meeting.",g:["Noise/Crowd"],d:"day"},
    {t:"Tables outside in warm months — sidewalk is wide enough not to feel exposed.",g:["Atmosphere & Vibe"],d:"day"},
    {t:"Block stays calm post-dinner.",g:["Safety & Comfort"],d:"night"},
  ],
  speakeasy: [
    {t:"Reservations only — show up without one and you're not getting in.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Two-drink minimum but the drinks justify it.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"No phones rule — relaxing, actually.",g:["Atmosphere & Vibe"],d:"night"},
    {t:"Quiet enough to actually talk.",g:["Noise/Crowd"],d:"night"},
    {t:"Door staff polite and discreet.",g:["Safety & Comfort"],d:"night"},
  ],
};

const NEIGH_AREA = {
  "Lower East Side": {nearby:[{name:"Katz's Deli", note:"Open till 2:45am"},{name:"Bowery 7-Eleven", note:"24hr"},{name:"Clinton St Baking Co", note:"Open till 11pm"}], street:"Orchard St well lit and busy on weekends; Rivington calmer after midnight.", spot:"Corner of Orchard & Stanton"},
  "East Village": {nearby:[{name:"Veselka", note:"24hr"},{name:"Tompkins Square Park", note:"Park closes 1am"},{name:"7-Eleven Ave A", note:"24hr"}], street:"St Marks busy until 2am; the avenues quieter east of First.", spot:"2nd Ave & St Marks"},
  "West Village": {nearby:[{name:"Sevilla", note:"Open till 1am"},{name:"Joe's Pizza", note:"Open till 4am"},{name:"Christopher Park", note:"Park closes 1am"}], street:"Bleecker and 7th Ave well-lit; side streets calmer but still active.", spot:"7th Ave South & Christopher St"},
  "Greenwich Village": {nearby:[{name:"Mamoun's Falafel", note:"Open till 5am"},{name:"Washington Sq Park", note:"Park closes midnight"},{name:"Duane Reade 8th St", note:"24hr"}], street:"Bleecker stays busy; quieter blocks east of 6th Ave.", spot:"6th Ave & W 4th"},
  "SoHo": {nearby:[{name:"Balthazar Bakery", note:"Open till 11pm"},{name:"Spring Lounge", note:"Open till 4am"},{name:"7-Eleven Broadway", note:"24hr"}], street:"Broadway and Spring well-lit; Mercer/Greene quieter at night.", spot:"Broadway & Spring"},
  "NoLita": {nearby:[{name:"Café Habana", note:"Open till midnight"},{name:"Ruby's", note:"Open till 1am"},{name:"Duane Reade Houston", note:"24hr"}], street:"Mulberry and Elizabeth active until late; cleaner blocks east of Bowery.", spot:"Mulberry & Prince"},
  "Tribeca": {nearby:[{name:"Walker's", note:"Open till 2am"},{name:"7-Eleven Hudson", note:"24hr"},{name:"Bubby's Tribeca", note:"Open till 11pm"}], street:"Streets quieter than other Manhattan areas — feels safe but plan rides.", spot:"Hudson & Franklin"},
  "FiDi": {nearby:[{name:"Black Iron Burger", note:"Open till 2am"},{name:"7-Eleven Pearl", note:"24hr"},{name:"Stone Street Tavern", note:"Open till 4am"}], street:"Quiet after 10 pm — fewer pedestrians, plan transit.", spot:"Pearl & Wall"},
  "Chelsea": {nearby:[{name:"Empire Diner", note:"Open till 1am"},{name:"Duane Reade 23rd", note:"24hr"},{name:"Tipsy Parson", note:"Open till midnight"}], street:"8th Ave well-lit; side streets quieter near the water.", spot:"8th Ave & 23rd"},
  "Flatiron": {nearby:[{name:"Eataly", note:"Open till 11pm"},{name:"Madison Sq Park", note:"Park closes midnight"},{name:"Duane Reade 23rd", note:"24hr"}], street:"5th Ave and Broadway busy; Madison quieter post-dinner.", spot:"Broadway & 23rd"},
  "Midtown": {nearby:[{name:"Joe Allen", note:"Open till 1am"},{name:"7-Eleven 8th Ave", note:"24hr"},{name:"Sardi's", note:"Open till midnight"}], street:"Dense and well-lit at most hours.", spot:"8th Ave & 46th"},
  "Hell's Kitchen": {nearby:[{name:"Empanada Mama", note:"24hr"},{name:"Duane Reade 9th Ave", note:"24hr"},{name:"Pocha 32", note:"Open till 4am"}], street:"9th and 10th Ave busy until 2am.", spot:"9th Ave & 46th"},
  "Upper East Side": {nearby:[{name:"E.A.T.", note:"Open till 10pm"},{name:"Duane Reade Lex", note:"24hr"},{name:"JG Melon", note:"Open till 2am"}], street:"Quiet residential — feels safe, plan rides.", spot:"Lexington & 76th"},
  "Upper West Side": {nearby:[{name:"Big Nick's", note:"Open till 2am"},{name:"Duane Reade Broadway", note:"24hr"},{name:"Cafe Lalo", note:"Open till midnight"}], street:"Broadway active till midnight; side streets very quiet.", spot:"Broadway & 79th"},
  "Harlem": {nearby:[{name:"Amy Ruth's", note:"Open till 11pm"},{name:"7-Eleven 125th", note:"24hr"},{name:"Red Rooster", note:"Open till midnight"}], street:"125th busy until late; residential streets quieter.", spot:"Lenox & 125th"},
  "Williamsburg": {nearby:[{name:"Kellogg's Diner", note:"24hr"},{name:"Duane Reade Bedford", note:"24hr"},{name:"Diner", note:"Open till midnight"}], street:"Bedford and Berry busy until 2am; Wythe quieter.", spot:"Bedford & N 7th"},
  "Bushwick": {nearby:[{name:"Tortilleria Mexicana", note:"Open till midnight"},{name:"7-Eleven Wyckoff", note:"24hr"},{name:"Roberta's", note:"Open till midnight"}], street:"Active near the venues, quieter on side streets — bring a friend or rideshare.", spot:"Wyckoff & Jefferson"},
  "Greenpoint": {nearby:[{name:"Peter Pan Donuts", note:"Open till 8pm"},{name:"7-Eleven Manhattan Ave", note:"24hr"},{name:"Glasserie", note:"Open till 11pm"}], street:"Manhattan Ave well-lit; quieter blocks west.", spot:"Manhattan Ave & Greenpoint Ave"},
  "Bed-Stuy": {nearby:[{name:"Saraghina", note:"Open till 11pm"},{name:"7-Eleven Nostrand", note:"24hr"},{name:"Peaches HotHouse", note:"Open till midnight"}], street:"Tompkins and Nostrand active; residential quieter.", spot:"Nostrand & Halsey"},
  "Crown Heights": {nearby:[{name:"Pels Pies", note:"Open till 11pm"},{name:"7-Eleven Franklin", note:"24hr"},{name:"Berg'n", note:"Open till midnight"}], street:"Franklin Ave busy late; side streets quieter.", spot:"Franklin & Eastern Pkwy"},
  "Park Slope": {nearby:[{name:"Korzo", note:"Open till midnight"},{name:"Duane Reade 7th Ave", note:"24hr"},{name:"Talde", note:"Open till 1am"}], street:"5th and 7th Ave well-lit; residential streets safe but quiet.", spot:"5th Ave & Union"},
  "Gowanus": {nearby:[{name:"Threes Brewing", note:"Open till midnight"},{name:"7-Eleven 4th Ave", note:"24hr"},{name:"Lavender Lake", note:"Open till 2am"}], street:"4th Ave busy; canal blocks quieter — plan rides.", spot:"4th Ave & 9th"},
  "Astoria": {nearby:[{name:"Neptune Diner", note:"24hr"},{name:"7-Eleven Steinway", note:"24hr"},{name:"Astor Bake Shop", note:"Open till 10pm"}], street:"30th Ave busy until 2am; Ditmars quieter.", spot:"30th Ave & 31st"},
  "LIC": {nearby:[{name:"Sage General Store", note:"Open till midnight"},{name:"7-Eleven Vernon", note:"24hr"},{name:"M. Wells Steakhouse", note:"Open till 11pm"}], street:"Vernon Blvd well-lit and active.", spot:"Vernon & 50th Ave"},
};

function buildPlace(row) {
  const [id, name, neigh, borough, type, addr, hours, arch, transitLine] = row;
  const bank = SIGNAL_BANK[arch] || SIGNAL_BANK.cocktail_bar;
  // Deterministic 4-signal pick from bank by id hash
  let h = 0; for (let i=0;i<id.length;i++) h = (h*31 + id.charCodeAt(i)) >>> 0;
  const picked = [];
  for (let i=0;i<4 && i<bank.length;i++) picked.push(bank[(h+i*3) % bank.length]);
  // Map to day/night observations
  const obs = {day:[], night:[]};
  picked.forEach(p => obs[p.d].push({text:p.t, tags:p.g}));
  // Ensure at least 2 day signals
  if (obs.day.length < 2) {
    bank.filter(b=>b.d==="day").slice(0,2-obs.day.length).forEach(p=>obs.day.push({text:p.t,tags:p.g}));
  }
  if (obs.night.length < 2) {
    bank.filter(b=>b.d==="night").slice(0,2-obs.night.length).forEach(p=>obs.night.push({text:p.t,tags:p.g}));
  }
  // Distance miles deterministic from id
  const d1 = (0.1 + (h%6)*0.1).toFixed(1);
  const d2 = (0.2 + ((h>>4)%5)*0.1).toFixed(1);
  const area = NEIGH_AREA[neigh] || NEIGH_AREA["Lower East Side"];
  return {
    id, name, neighbourhood: neigh, borough, type, address: addr, hours,
    coordinates: null,
    tags: [type.split("/")[0], neigh.split(/[\s,]/)[0]],
    transit: { name: transitLine, tags: ["Well Lit"], fromNYU: "" },
    transitList: [
      { label: transitLine, miles: d1+" miles" },
      { label: "Local bus stop", miles: d2+" miles" },
    ],
    observations: obs,
    areaActivity: [area.street, "Nearby spots open late.", "Rideshares typical."],
    areaInfo: {
      nearbyOpen: area.nearby,
      streetConditions: area.street,
      rideshare: { wait: "3–5 min", spot: area.spot },
    },
    image: null,
  };
}

const NEW_VENUES = [
  // ── LOWER EAST SIDE ──
  ["theback","The Back Room","Lower East Side","Manhattan","Cocktail Bar","102 Norfolk St","Open till 4am","speakeasy","Delancey St F/M/J/Z"],
  ["doublechicken","Double Chicken Please","Lower East Side","Manhattan","Cocktail Bar","115 Allen St","Open till 2am","cocktail_bar","Grand St B/D"],
  ["parcelle","Parcelle","Lower East Side","Manhattan","Wine Bar","135 Delancey St","Open till midnight","wine_bar","Delancey St F/M/J/Z"],
  ["mehanata","Mehanata","Lower East Side","Manhattan","Club","113 Ludlow St","Open till 4am","club","Delancey St F/M/J/Z"],
  ["pianos","Pianos","Lower East Side","Manhattan","Bar/Music Venue","158 Ludlow St","Open till 4am","music_venue","Delancey St F/M/J/Z"],
  ["forgtmenot","Forgtmenot","Lower East Side","Manhattan","Bar/Cafe","138 Division St","Open till 2am","cafe","East Broadway F"],
  ["flowershop","The Flower Shop","Lower East Side","Manhattan","Bar/Restaurant","107 Eldridge St","Open till 2am","cocktail_bar","Grand St B/D"],
  ["barrevival","Bar Revival","Lower East Side","Manhattan","Cocktail Bar","129 Division St","Open till 1am","cocktail_bar","East Broadway F"],
  // ── EAST VILLAGE ──
  ["deathandco","Death & Co","East Village","Manhattan","Cocktail Bar","433 E 6th St","Open till 1am","cocktail_bar","Astor Pl 6"],
  ["pdt","PDT","East Village","Manhattan","Cocktail Bar","113 St Marks Pl","Open till 2am","speakeasy","Astor Pl 6"],
  ["amorbar","Amor y Amargo","East Village","Manhattan","Cocktail Bar","443 E 6th St","Open till midnight","cocktail_bar","Astor Pl 6"],
  ["wayland","The Wayland","East Village","Manhattan","Cocktail Bar","700 E 9th St","Open till 4am","cocktail_bar","1 Av L"],
  ["niagara","Niagara","East Village","Manhattan","Bar","112 Avenue A","Open till 4am","dive_bar","1 Av L"],
  ["angelshare","Angel's Share","East Village","Manhattan","Cocktail Bar","45 Grove St","Open till 1am","speakeasy","Astor Pl 6"],
  ["porchlight","Porchlight","East Village","Manhattan","Cocktail Bar","271 11th Ave","Open till midnight","cocktail_bar","23 St C/E"],
  // ── WEST VILLAGE ──
  ["employees","Employees Only","West Village","Manhattan","Cocktail Bar","510 Hudson St","Open till 4am","cocktail_bar","Christopher St 1"],
  ["dante","Dante","West Village","Manhattan","Bar/Cafe","79-81 MacDougal St","Open till midnight","cafe","W 4 St A/C/E"],
  ["chumleys","Chumley's","West Village","Manhattan","Restaurant","86 Bedford St","Open till midnight","speakeasy","Christopher St 1"],
  ["buvette","Buvette","West Village","Manhattan","Bistro","42 Grove St","Open till 2am","bistro","Christopher St 1"],
  ["happiest","The Happiest Hour","West Village","Manhattan","Cocktail Bar","121 W 10th St","Open till 4am","cocktail_bar","W 4 St A/C/E"],
  ["barsardine","Bar Sardine","West Village","Manhattan","Restaurant/Bar","183 W 10th St","Open till 1am","wine_bar","Christopher St 1"],
  ["analogue","Analogue","Greenwich Village","Manhattan","Bar/Music Venue","19 W 8th St","Open till 4am","music_venue","8 St NYU R/W"],
  // ── SOHO / NOLITA ──
  ["balthazar","Balthazar","SoHo","Manhattan","Bistro","80 Spring St","Open till midnight","bistro","Spring St 6"],
  ["springlounge","Spring Lounge","SoHo","Manhattan","Bar","48 Spring St","Open till 4am","dive_bar","Spring St 6"],
  ["pegu","Pegu Club","SoHo","Manhattan","Cocktail Bar","77 W Houston St","Open till 2am","cocktail_bar","Bleecker St 6"],
  ["nolitahouse","Nolita House","NoLita","Manhattan","Bar/Restaurant","47 E Houston St","Open till midnight","wine_bar","Bleecker St 6"],
  ["fanellis","Fanelli Cafe","SoHo","Manhattan","Restaurant/Bar","94 Prince St","Open till 1am","bistro","Prince St N/R"],
  // ── CHELSEA / FLATIRON ──
  ["thetippler","The Tippler","Chelsea","Manhattan","Cocktail Bar","425 W 15th St","Open till 2am","cocktail_bar","8 Av L"],
  ["twothirty","230 Fifth","Flatiron","Manhattan","Rooftop","230 5th Ave","Open till 4am","rooftop","23 St N/R/W"],
  ["bathtubgin","Bathtub Gin","Chelsea","Manhattan","Cocktail Bar","132 9th Ave","Open till 2am","speakeasy","14 St A/C/E"],
  ["fig19","Fig 19","Chelsea","Manhattan","Cocktail Bar","131 Chrystie St","Open till 2am","cocktail_bar","Bowery J/Z"],
  // ── MIDTOWN / HK ──
  ["bemelmans","Bemelmans Bar","Upper East Side","Manhattan","Cocktail Bar","35 E 76th St","Open till 1am","cocktail_bar","77 St 6"],
  ["campbell","The Campbell","Midtown","Manhattan","Cocktail Bar","15 Vanderbilt Ave","Open till 1am","cocktail_bar","Grand Central 4/5/6/7"],
  ["flatironlounge","Flatiron Lounge","Flatiron","Manhattan","Cocktail Bar","37 W 19th St","Open till 2am","cocktail_bar","23 St F/M"],
  ["rumhouse","The Rum House","Hell's Kitchen","Manhattan","Cocktail Bar","228 W 47th St","Open till 4am","cocktail_bar","49 St N/R/W"],
  // ── UES / UWS ──
  ["cafecarlyle","Café Carlyle","Upper East Side","Manhattan","Music Venue","35 E 76th St","Open till 1am","music_venue","77 St 6"],
  ["deadpoet","The Dead Poet","Upper West Side","Manhattan","Bar","450 Amsterdam Ave","Open till 4am","dive_bar","81 St 1"],
  ["aubergine","Aubergine","Upper East Side","Manhattan","Bistro","1213 Lexington Ave","Open till midnight","bistro","86 St 4/5/6"],
  // ── HARLEM ──
  ["sylvias","Sylvia's","Harlem","Manhattan","Restaurant","328 Malcolm X Blvd","Open till 10pm","restaurant","125 St 2/3"],
  ["sixtyseven","67 Orange Street","Harlem","Manhattan","Cocktail Bar","2082 Frederick Douglass Blvd","Open till 2am","cocktail_bar","125 St A/B/C/D"],
  ["shrine","Shrine","Harlem","Manhattan","Music Venue","2271 Adam Clayton Powell Jr Blvd","Open till 4am","music_venue","135 St 2/3"],
  ["vinateria","Vinatería","Harlem","Manhattan","Wine Bar","2211 Frederick Douglass Blvd","Open till midnight","wine_bar","125 St A/B/C/D"],
  // ── WILLIAMSBURG ──
  ["laserwolf","Laser Wolf","Williamsburg","Brooklyn","Restaurant","97 Wythe Ave","Open till 11pm","restaurant","Bedford Av L"],
  ["babysallright","Baby's All Right","Williamsburg","Brooklyn","Music Venue","146 Broadway","Open till 4am","music_venue","Marcy Av J/M/Z"],
  ["hoteldelmano","Hotel Delmano","Williamsburg","Brooklyn","Cocktail Bar","82 Berry St","Open till 2am","cocktail_bar","Bedford Av L"],
  ["maisonpremiere","Maison Premiere","Williamsburg","Brooklyn","Cocktail Bar","298 Bedford Ave","Open till 2am","cocktail_bar","Bedford Av L"],
  ["donnabar","Donna","Williamsburg","Brooklyn","Cocktail Bar","27 Broadway","Open till 4am","cocktail_bar","Marcy Av J/M/Z"],
  ["kinfolk","Kinfolk","Williamsburg","Brooklyn","Bar/Music Venue","94 Wythe Ave","Open till 4am","music_venue","Bedford Av L"],
  // ── BUSHWICK ──
  ["houseofyes","House of Yes","Bushwick","Brooklyn","Club","2 Wyckoff Ave","Open till 4am","club","Jefferson St L"],
  ["nowadays","Nowadays","Bushwick","Brooklyn","Bar/Club","56-06 Cooper Ave","Open till 4am","club","Jefferson St L"],
  ["jupiterdisco","Jupiter Disco","Bushwick","Brooklyn","Cocktail Bar","1237 Flushing Ave","Open till 4am","cocktail_bar","Morgan Av L"],
  ["thejohnsons","The Johnsons","Bushwick","Brooklyn","Bar","369 Troutman St","Open till 4am","dive_bar","Jefferson St L"],
  ["birdys","Birdy's","Bushwick","Brooklyn","Bar","474 Wyckoff Ave","Open till 2am","cocktail_bar","Jefferson St L"],
  // ── GREENPOINT ──
  ["archestratus","Archestratus","Greenpoint","Brooklyn","Cafe","160 Huron St","Open till 8pm","cafe","Greenpoint Av G"],
  ["thediamond","The Diamond","Greenpoint","Brooklyn","Bar","43 Franklin St","Open till 4am","dive_bar","Greenpoint Av G"],
  ["pauliegees","Paulie Gee's","Greenpoint","Brooklyn","Restaurant","60 Greenpoint Ave","Open till midnight","restaurant","Greenpoint Av G"],
  ["brouwerij","Brouwerij Lane","Greenpoint","Brooklyn","Bar","78 Greenpoint Ave","Open till midnight","wine_bar","Greenpoint Av G"],
  // ── BED-STUY / CROWN HEIGHTS ──
  ["butterscotch","Butter & Scotch","Crown Heights","Brooklyn","Bar","818 Franklin Ave","Open till 2am","cocktail_bar","Franklin Av 2/3/4/5"],
  ["friendsandlovers","Friends and Lovers","Crown Heights","Brooklyn","Bar/Music Venue","641 Classon Ave","Open till 4am","club","Classon Av G"],
  ["barbes","Barbès","Park Slope","Brooklyn","Music Venue","376 9th St","Open till 2am","music_venue","7 Av F/G"],
  ["playgroundbk","Playground","Bed-Stuy","Brooklyn","Bar","1234 Bedford Ave","Open till 2am","cocktail_bar","Bedford-Nostrand Avs G"],
  // ── PARK SLOPE / GOWANUS ──
  ["publicrecords","Public Records","Gowanus","Brooklyn","Bar/Club","233 Butler St","Open till 2am","club","Bergen St 2/3"],
  ["threesbrewing","Threes Brewing","Gowanus","Brooklyn","Bar","333 Douglass St","Open till midnight","wine_bar","Union St R"],
  ["freddysbar","Freddy's Bar","Park Slope","Brooklyn","Bar","627 5th Ave","Open till 4am","dive_bar","Prospect Av R"],
  ["fourthavpub","4th Ave Pub","Park Slope","Brooklyn","Bar","76 4th Ave","Open till 4am","dive_bar","Atlantic Av Bgn 2/3/4/5"],
  // ── ASTORIA / LIC ──
  ["astorroom","The Astor Room","Astoria","Queens","Cocktail Bar","34-12 36th St","Open till 1am","cocktail_bar","Steinway St M/R"],
  ["sweetafton","Sweet Afton","Astoria","Queens","Bar","30-09 34th St","Open till 4am","dive_bar","30 Av N/W"],
  ["dominies","Dominie's Astoria","Astoria","Queens","Bar","34-07 30th Ave","Open till 4am","dive_bar","30 Av N/W"],
  ["dutchkills","Dutch Kills","LIC","Queens","Cocktail Bar","27-24 Jackson Ave","Open till 2am","cocktail_bar","Queensboro Plaza N/W/7"],
];

NEW_VENUES.forEach(row => PLACES.push(buildPlace(row)));

const PLACE_MAP = {};
PLACES.forEach(p => { PLACE_MAP[p.name.toLowerCase()] = p; PLACE_MAP[p.id] = p; });

// ── STATIC SUMMARIES ─────────────────────────────────────────────────────────
const SUMMARIES = {
  "schmuck|day":    "A low-key wine bar that's easy to settle into during the afternoon.",
  "schmuck|night":  "Fills up after 10 pm — the back stays quieter than the front.",
  "schmuck|overall":"A neighbourhood wine bar that shifts from calm to crowded after dark.",
  "superbueno|day":    "Relaxed lunch crowd, mostly locals — easy to walk in before 6.",
  "superbueno|night":  "Livelier in the evening, especially when there's music on.",
  "superbueno|overall":"A Latin bar-restaurant that's calm by day and energetic by night.",
  "attaboy|day":    "Rarely busy before 7 — good time to get the bartenders' full attention.",
  "attaboy|night":  "Standing room only after 10, with a low-key crowd despite the volume.",
  "attaboy|overall":"A no-menu cocktail bar that gets packed late but stays surprisingly calm.",
  "julius|day":    "One of NYC's oldest bars — afternoons here are quiet and unhurried.",
  "julius|night":  "Busier after 9 but never chaotic — easy to find a spot even on weekends.",
  "julius|overall":"A historic West Village bar with a relaxed, mixed crowd at any hour.",
  "gage|day":    "Lunch is quieter — easier to get a table and have a real conversation.",
  "gage|night":  "Dinner fills the room and the noise rises, but it stays manageable.",
  "gage|overall":"A restored Brooklyn classic — more relaxed at lunch, livelier at dinner.",
  "saraghina|day":    "Brunch draws a queue — the garden out back is calm on weekday afternoons.",
  "saraghina|night":  "Garden seating stays quieter than the main room after dark.",
  "saraghina|overall":"A neighbourhood restaurant with a calm garden and a familiar crowd.",
  // Lower East Side additions
  "barriochino|day":    "A mezcal bar that's easy and unhurried during afternoon hours.",
  "barriochino|night":  "Warm and intimate even when busy — a reliable LES option.",
  "barriochino|overall":"A neighbourhood mezcal bar, calm by day and cosy by night.",
  "thetenbells|day":    "Candlelit and quiet — good for a slow glass of natural wine.",
  "thetenbells|night":  "Intimate and crowded by 10 pm — one of LES's best wine bars.",
  "thetenbells|overall":"A natural wine bar that gets packed fast but stays atmospheric.",
  "mrpurple|day":       "Rooftop views of lower Manhattan — best before the evening crowds.",
  "mrpurple|night":     "Busy on weekends — the city views at night are worth it.",
  "mrpurple|overall":   "A hotel rooftop bar with genuine Manhattan skyline views.",
  "beautybarles|day":   "Kitschy dive bar energy — relaxed and cheap in the early hours.",
  "beautybarles|night": "One of the real late-night spots — loud and packed after midnight.",
  "beautybarles|overall":"A late-night LES dive with cheap drinks and a lively crowd.",
  "pigandkhao|day":     "Relaxed lunch service — easier to get in than at dinner.",
  "pigandkhao|night":   "Loud and energetic — the open kitchen adds to the buzz.",
  "pigandkhao|overall": "A Southeast Asian restaurant that's calm at lunch and lively at dinner.",
  "welcometothejohnsons|day":   "Classic dive bar — pool table, cheap beer, no pretension.",
  "welcometothejohnsons|night": "Standing room only by midnight — a true LES institution.",
  "welcometothejohnsons|overall":"A no-frills dive bar that fills up reliably on weekends.",
  "happyending|day":    "Good for early evening cocktails in a distinctive tiled space.",
  "happyending|night":  "DJs and a dark lower level — not a talking bar late.",
  "happyending|overall":"A former spa turned late-night bar with a distinctive atmosphere.",
  "leturtle|day":       "Good natural light and a relaxed lunch pace.",
  "leturtle|night":     "Dinner fills up — the bar stays open after the kitchen.",
  "leturtle|overall":   "A French-influenced LES restaurant that transitions well into a late bar.",
  // West Village additions
  "employeesonly|day":  "Evening bar — best visited early to get a seat at the bar.",
  "employeesonly|night":"Busy most nights with exceptional cocktails and a late licence.",
  "employeesonly|overall":"One of NYC's best cocktail bars — busy but worth the wait.",
  "buvette|day":        "A cramped French bistro best enjoyed at a slow weekend brunch.",
  "buvette|night":      "Intimate and candlelit — loud when full but reliably atmospheric.",
  "buvette|overall":    "A West Village institution — small, crowded, and very good.",
  "littlebranch|day":   "Opens evenings — a genuine speakeasy feel with live jazz.",
  "littlebranch|night": "Packed after 10 pm — arrive early to get a proper seat.",
  "littlebranch|overall":"A basement cocktail bar with live jazz and a genuine speakeasy atmosphere.",
  "whitehorsetavern|day":   "Afternoon pints in a bar that's been open since 1880.",
  "whitehorsetavern|night": "Busy but never overwhelming — a West Village constant.",
  "whitehorsetavern|overall":"A historic Village bar — outdoor seating fills up first.",
  "villagevanguard|day":    "Evening shows only — book in advance, sets sell out.",
  "villagevanguard|night":  "The best jazz venue in the city — quiet during performances.",
  "villagevanguard|overall":"A legendary jazz club — shows require booking and a minimum.",
  "fedora|day":         "A relaxed brunch spot with a reliable basement bar.",
  "fedora|night":       "Dinner fills up — the bar downstairs is a good late option.",
  "fedora|overall":     "A West Village favourite with a good bar below the restaurant.",
  "thehalfking|day":    "A literary bar with a great outdoor patio and solid food.",
  "thehalfking|night":  "Busier on weekends but conversation-friendly throughout.",
  "thehalfking|overall":"A Chelsea bar with a strong food offer and a low-key crowd.",
  "motherofpearl|day":  "Opens mid-afternoon — fun tiki drinks without the evening crowds.",
  "motherofpearl|night":"Loud and celebratory — ideal for groups and birthdays.",
  "motherofpearl|overall":"A tiki bar that leans into the fun — great for groups.",
  // Williamsburg additions
  "maisonpremiere|day":   "One of the best garden bars in Brooklyn — good oyster happy hour.",
  "maisonpremiere|night": "Very popular — waits are common but the cocktails justify it.",
  "maisonpremiere|overall":"A Williamsburg institution with serious cocktails and a great garden.",
  "idesbar|day":          "Wythe Hotel rooftop — Manhattan views are best before evening crowds.",
  "idesbar|night":        "Busy on weekends — arrive before 8 pm for a good spot.",
  "idesbar|overall":      "A rooftop bar with genuine Manhattan skyline views across the river.",
  "hoteldelmano|day":     "Dark wood and classic cocktail bar atmosphere from early evening.",
  "hoteldelmano|night":   "Fills steadily without overwhelming — intimate even when busy.",
  "hoteldelmano|overall": "A classic cocktail bar that stays intimate despite its popularity.",
  "thewilliamvale|day":   "Sweeping skyline views — less crowded on weekday afternoons.",
  "thewilliamvale|night": "One of the best night views in Brooklyn — busy on weekends.",
  "thewilliamvale|overall":"A rooftop bar with the widest Manhattan views in Williamsburg.",
  "marlowandsons|day":    "A neighbourhood brunch staple — counter seats good for solo visits.",
  "marlowandsons|night":  "Dinner is quieter than brunch — intimate and well-suited to a date.",
  "marlowandsons|overall":"A reliable neighbourhood restaurant with good bar seating.",
  "nightsandweekends|day":  "Opens evenings — cheap, good soundtrack, unpretentious.",
  "nightsandweekends|night":"One of the go-to late spots in Williamsburg — cheap and packed.",
  "nightsandweekends|overall":"A late-night Williamsburg bar — cheap drinks and a good crowd.",
  "stanselm|day":         "Bar area good for drinks before your table — dinner only.",
  "stanselm|night":       "Buzzy and loud in a good way — one of Brooklyn's best steaks.",
  "stanselm|overall":     "A Williamsburg steakhouse with bar seats for walk-ins.",
  "pearlsbar|day":        "Classic dive bar — pool table, cheap beer, local crowd.",
  "pearlsbar|night":      "One of the few reliably open 4 am bars in Brooklyn.",
  "pearlsbar|overall":    "A late-night dive bar on the quieter side of Williamsburg.",
  "reynard|day":          "Airy hotel restaurant — good for a relaxed brunch.",
  "reynard|night":        "Solid dinner with wood-fired dishes — bar area good for walk-ins.",
  "reynard|overall":      "The Wythe Hotel restaurant — relaxed and good quality.",
  // Downtown Brooklyn / Cobble Hill additions
  "cloverclub|day":       "One of the best cocktail bars in Brooklyn — elegant and unhurried.",
  "cloverclub|night":     "Gets busy but well-designed — rarely feels overcrowded.",
  "cloverclub|overall":   "A Cobble Hill cocktail institution — excellent drinks and atmosphere.",
  "frankies457|day":      "A neighbourhood institution with a beautiful back garden.",
  "frankies457|night":    "Intimate Italian dinner — the garden is exceptional on warm nights.",
  "frankies457|overall":  "A Carroll Gardens classic with a legendary back garden.",
  "junewinebar|day":      "A relaxed afternoon wine bar with a careful natural wine selection.",
  "junewinebar|night":    "Conversation-friendly and intimate — a quieter Brooklyn option.",
  "junewinebar|overall":  "A Cobble Hill natural wine bar — calm and well-curated.",
  "butterandscotch|day":  "Cocktails and desserts — the combination is genuinely fun.",
  "butterandscotch|night":"Festive and busy on weekends — great for groups.",
  "butterandscotch|overall":"A Crown Heights bar-bakery with boozy milkshakes and good vibes.",
  "bergn|day":            "A food hall format — easy for groups with different tastes.",
  "bergn|night":          "Gets loud and busy on weekends — reliable group spot.",
  "bergn|overall":        "A Crown Heights food hall with good beer and communal seating.",
  "hinterlands|day":      "A low-key Atlantic Ave bar — good for an unpretentious afternoon.",
  "hinterlands|night":    "Neighbourhood bar without the tourist layer — reliable.",
  "hinterlands|overall":  "A Downtown Brooklyn bar close to the best transit hub in the borough.",
  "theosprey|day":        "1 Hotel bar with harbour views — good coffee and relaxed brunch.",
  "theosprey|night":      "Bridge and skyline views at night — quieter than Manhattan equivalents.",
  "theosprey|overall":    "A hotel bar with exceptional views of the Brooklyn Bridge.",
  "grandarmy|day":        "Oyster bar and cocktails — excellent raw bar at lunch.",
  "grandarmy|night":      "Busy on weekends — good cocktail programme near Atlantic Ave.",
  "grandarmy|overall":    "A Downtown Brooklyn oyster bar with strong drinks.",
  "colonie|day":          "A neighbourhood restaurant that does one of the better area brunches.",
  "colonie|night":        "Intimate dinner — noise stays manageable even when full.",
  "colonie|overall":      "A Brooklyn Heights restaurant with a calm, local atmosphere.",
  "popina|day":           "A waterfront restaurant with outdoor seating and harbour views.",
  "popina|night":         "Quiet neighbourhood dinner — plan transport in advance.",
  "popina|overall":       "A low-key waterfront restaurant on the quieter Columbia St corridor.",

};

