// Looks up every venue in data.js on Google Places (New) and writes photos.js.
//
//   node tools/fetch-photos.mjs
//
// Uses the GOOGLE_KEY already in whspr-13.html (override with GOOGLE_MAPS_API_KEY).
// Also writes tools/photo-matches.txt so wrong matches can be spotted.

import { readFileSync, writeFileSync } from "node:fs";
import vm from "node:vm";

const root = new URL("..", import.meta.url);
const html = readFileSync(new URL("whspr-13.html", root), "utf8");
const key = process.env.GOOGLE_MAPS_API_KEY || html.match(/const GOOGLE_KEY = "([^"]+)"/)?.[1];
if (!key) { console.error("No API key found"); process.exit(1); }

const places = vm.runInNewContext(readFileSync(new URL("data.js", root), "utf8") + ";PLACES");

async function lookup(p) {
  const res = await fetch("https://places.googleapis.com/v1/places:searchText", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Goog-Api-Key": key,
      "X-Goog-FieldMask": "places.id,places.displayName,places.formattedAddress,places.photos",
    },
    body: JSON.stringify({ textQuery: `${p.name}, ${p.address}, New York, NY` }),
  });
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
  return (await res.json()).places?.[0];
}

// Google names that are genuinely the same venue under another name
const ALIASES = {
  "PDT": "Please Don't Tell",
  "Chumley's": "The Eighty Six",
  "Ides Bar": "Wythe Hotel",               // rooftop bar of the hotel
  "The Astor Room": "Kaufman Astoria Studios", // inside the studios
  "4th Ave Pub": "Fourth Avenue Pub",
};

const norm = (s) => s.toLowerCase().normalize("NFD").replace(/&/g, "and")
  .replace(/\s+-\s+.*$/, "").replace(/[^a-z0-9]/g, "").replace(/^the/, "");

// Reject matches to a different business (closed venues often resolve to whatever took over the address)
function sameVenue(p, match) {
  const a = norm(ALIASES[p.name] || p.name), b = norm(match.displayName?.text || "");
  return a.includes(b) || b.includes(a);
}

const photos = {};
const report = [];
for (const p of places) {
  try {
    const match = await lookup(p);
    const ok = match && sameVenue(p, match);
    const photo = ok && match.photos?.[0]?.name;
    if (photo) photos[p.id] = photo;
    const status = photo ? "OK  " : match && !ok ? "SKIP" : "MISS";
    report.push(`${status} ${p.name} (${p.address}) → ${match ? `${match.displayName?.text} — ${match.formattedAddress}` : "no match"}`);
  } catch (e) {
    report.push(`ERR  ${p.name}: ${e.message}`);
  }
}

writeFileSync(new URL("photos.js", root),
  "// Generated by tools/fetch-photos.mjs — venue id → Google Places photo resource name.\n" +
  `const PLACE_PHOTOS = ${JSON.stringify(photos, null, 2)};\n`);
writeFileSync(new URL("tools/photo-matches.txt", root), report.join("\n") + "\n");
console.log(`${Object.keys(photos).length}/${places.length} venues have photos. Review tools/photo-matches.txt.`);
